DEPARTMENTS = {
    "ACCOUNTANCY": 7,
    "BANKING AND FINANCE": 6,
    "CIVIL ENGINEERING": 4,
    "COMPUTER ENGINEERING": 3,
    "COMPUTER SCIENCE": 1,
    "ENVIRONMENTAL BIOLOGY": 9,
    "FOOD TECHNOLOGY": 2,
    "MECHANICAL ENGINEERING": 5,
    "MICROBIOLOGY": 8
}