DEPARTMENTS = {
    "ACCOUNTANCY": 25,
    "BANKING AND FINANCE": 24,
    "CIVIL ENGINEERING": 22,
    "COMPUTER ENGINEERING": 21,
    "COMPUTER SCIENCE": 19,
    "ENVIRONMENTAL BIOLOGY": 27,
    "FOOD TECHNOLOGY": 20,
    "MECHANICAL ENGINEERING": 23,
    "MICROBIOLOGY": 26
}